### PR TITLE
MM-17424 Setting to enable/disable fixed sidebar

### LINKED ISSUE #2911: Channel sidebar remains open on mobile device
#### Summary
Channel sidebar remains open on mobile device can't hide it which makes it unusable in portrait orientation of device.

#### Environment Information

- Device Name: moto g(7)
- OS Version: Android 9
- Mattermost App Version: 1.20.0

#### Steps to reproduce
In device portrait orientation channel sidebar remains open no ability to hide it.

#### Expected behavior
Channel sidebar should be allowed to hide by sweep left gesture (as in previous app version).

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Add a setting for tablets to enable/disable the fixed channel/team sidebar

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-17424
Resolves #2911

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] Includes text changes and localization file updates

### CODE REVIEW

**Comment by esethna** [comment]
Cherry pick approved as per https://community-daily.mattermost.com/core/pl/x33h5io1dinj8ee3u5r8rznije

File: app/components/sidebars/main/main_sidebar.js [hunk 1]
```diff
@@ -142,6 +147,13 @@ export default class ChannelSidebar extends Component {
         }
     };
 
+    handlePermanentSidebar = async () => {
+        if (DeviceTypes.IS_TABLET && this.mounted) {
+            const enabled = await AsyncStorage.getItem(DeviceTypes.PERMANENT_SIDEBAR_SETTINGS);
```
Comment (migbot) [inline app/components/sidebars/main/main_sidebar.js]: Any chance that `this.mounted` could be false after the `await` call is finished?

File: app/screens/channel/channel_nav_bar/channel_nav_bar.js [hunk 2]
```diff
@@ -55,6 +61,14 @@ export default class ChannelNavBar extends PureComponent {
         }
     };
 
+    handlePermanentSidebar = () => {
+        if (DeviceTypes.IS_TABLET && this.mounted) {
```
Comment (migbot) [inline app/screens/channel/channel_nav_bar/channel_nav_bar.js]: Same `this.mounted` question as above.

File: app/components/sidebars/main/main_sidebar.js (hunk 1 above)
Comment (enahum) [reply app/components/sidebars/main/main_sidebar.js]: not that I can think of.. what are you thinking?

Comment (migbot) [reply app/components/sidebars/main/main_sidebar.js]: We want to avoid setting the state if the component has unmounted.

Comment (enahum) [reply app/components/sidebars/main/main_sidebar.js]: yes I get that, but when do you think this can happen?

Comment (migbot) [reply app/components/sidebars/main/main_sidebar.js]: Oh just wondering if there could be a scenario where `PERMANENT_SIDEBAR_SETTINGS` gets emitted while it's mounted, but then unmounts prior to AsyncStorage finishing?

Comment (enahum) [reply app/components/sidebars/main/main_sidebar.js]: oh, that is only being called when changing the setting manually, so this component is already mounted

Comment (migbot) [reply app/components/sidebars/main/main_sidebar.js]: To be safe we can check `this.mounted` right before `setState`

Comment (migbot) [reply app/components/sidebars/main/main_sidebar.js]: > oh, that is only being called when changing the setting manually, so this component is already mounted

Gotcha.

File: app/screens/channel/channel_nav_bar/channel_nav_bar.test.js [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+    test('should set the permanentSidebar state if Tablet', async () => {
+        const wrapper = shallow(
+            <ChannelNavBar {...baseProps}/>
+        );
+
+        DeviceTypes.IS_TABLET = true;
+
+        await wrapper.instance().handlePermanentSidebar();
+
+        expect(wrapper.state('permanentSidebar')).toBeDefined();
```
Comment (saturninoabril) [inline app/screens/channel/channel_nav_bar/channel_nav_bar.test.js]: The above assertion of undefined may make sense but if defined, I feel like we should specifically assert if that's true or false.

File: app/screens/settings/clock_display/clock_display.android.js [hunk 4]
```diff
@@ -19,7 +19,7 @@ import ClockDisplayBase from './clock_display_base';
 export default class ClockDisplay extends ClockDisplayBase {
     static propTypes = {
         showModal: PropTypes.bool.isRequired,
-        militaryTime: PropTypes.bool.isRequired,
+        militaryTime: PropTypes.string.isRequired,
```
Comment (saturninoabril) [inline app/screens/settings/clock_display/clock_display.android.js]: Wow, it's been there for ages :)
