### PR TITLE
Use system default for vibration pattern

### LINKED ISSUE #1216: Non-standard vibration pattern
#### Summary
The vibration pattern for Android push notifications is unusual and distracting / non-standard.

#### Environment Information
- Device Name: Nexus 5X
- OS Version: 8.0.0
- Mattermost App Version: 
- Mattermost Server Version: 4.4.1

#### Steps to reproduce
- Enable notifications with vibrations
- Trigger a notification on your Android device

#### Expected behavior
The vibration on push notifications should just use the default vibration pattern.

#### Possible fixes
I guess the vibration pattern is set here: [CustomPushNotification.java#L269](https://github.com/mattermost/mattermost-mobile/blob/master/android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java#L269)
Maybe useful Android SDK docu: [Notification.html#DEFAULT_VIBRATE](https://developer.android.com/reference/android/app/Notification.html#DEFAULT_VIBRATE)

### PR DESCRIPTION
**Pull request by alexrashed**
#### Summary
Change the vibration pattern for Android to use the system default.

#### Ticket Link
will close #1216

#### Device Information
This PR was tested on: Nexus 5X - Android 8.0.0

### CODE REVIEW

File: android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java [hunk 1]
```diff
@@ -265,8 +265,8 @@ protected void postNotification(int id, Notification notification) {
 
         boolean vibrate = notificationPreferences.getShouldVibrate();
         if (vibrate) {
-            // Each element then alternates between delay, vibrate, sleep, vibrate, sleep
-            notification.setVibrate(new long[] {1000, 1000, 500, 1000, 500});
+            // use the system default for vibration
+            notification.setDefaults(Notification.DEFAULT_VIBRATE);
```
Comment (enahum) [inline android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java]: Will this affect the light and sound preferences?

Comment (alexrashed) [reply android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java]: According to the documentation, this means that only the vibration settings should be inherited from the system defaults:
[Notification.Builder.html#setDefaults(int)](https://developer.android.com/reference/android/app/Notification.Builder.html#setDefaults(int))
"Set which notification properties will be inherited from system defaults."
The settings for light and sound are set explicitly and should therefore (in my opinion) not be touched by that.

Actually in my opinion we could also just use the default settings for sound and lights (building the bitmap depending on the settings instead of calling setLights and setSound and using setDefault once), but I wasn't sure if there's an intention for the custom light / sound.

Comment (enahum) [reply android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java]: We do have settings that let you change the sound and lights so default for them are not an option

Comment (enahum) [reply android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java]: I’ll be testing this tomorrow to see if the vibrate default setting works as expected.

Thanks so much for this, I’ll let you know if it works
