### PR TITLE
Fix share from SwiftKey Keyboard and clear temp files

### LINKED ISSUE #1532: Insert gif in message crashs app
#### Summary
When I want send over my swiftkey keyboard in the android app a gif as message, the application crashs reproducable.

#### Environment Information

- Device Name: HTC 10
- OS Version: Android 8.0.0 Security Patch-Level 1st Dec. 2017, 3.16.401.2
- Mattermost App Version: 1.6.1 (Build 86)
- Mattermost Server Version: 4.8.0

#### Steps to reproduce
Open channel or private chat and send gif over swiftkey keyboard

#### Expected behavior
Can insert gif as image into channel/private chat

#### Observed behavior
"Critical Error Occured!"
"This is embarrassing. We sincerely appologize for this."

Details -> "java.lang.IllegalArgumentException: column '_data' does not exists at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333) at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:92) ....

By the way ... it should be possible, send the error message directly to you over "Report error" button or copy text and send. Currently error details can only be show without mark and copy.

#### Possible fixes
I don't know

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Fixes a crash when trying to share content from a custom keyboard (SwiftKey in this case was used to test) and also removes the temp files from the cache dir if there were some created while sharing content.

#### Ticket Link
Fixes #1532 

#### Device Information
This PR was tested on: 
* Android 7.1.1 Emulator

### CODE REVIEW

File: android/app/src/main/java/com/mattermost/share/ShareModule.java [hunk 1]
```diff
@@ -40,6 +40,7 @@
     public ShareModule(ReactApplicationContext reactContext) {
         super(reactContext);
     }
+    private String tempFolder;
```
Comment (lieut-data) [inline android/app/src/main/java/com/mattermost/share/ShareModule.java]: Worth using a `Path` here instead of having to juggle `/` on a `String`?

File: android/app/src/main/java/com/mattermost/share/ShareModule.java [hunk 2]
```diff
@@ -78,6 +80,8 @@ public void close(ReadableMap data) {
                 }
             }
         }
+
+        RealPathUtil.deleteTempFiles(this.tempFolder);
```
Comment (lieut-data) [inline android/app/src/main/java/com/mattermost/share/ShareModule.java]: Is this `tempFolder` used for other purposes? If not, any reason we don't just delete all files? If yes, any reason not to create a folder dedicated as such and from which we can delete all files?

File: android/app/src/main/java/com/mattermost/share/RealPathUtil.java [hunk 3]
```diff
@@ -172,4 +176,22 @@ public static String getMimeType(String filePath) {
         File file = new File(filePath);
         return getMimeType(file);
     }
+
+    public static void deleteTempFiles(final String tempFolder) {
+        try {
+            File dir = new File(tempFolder);
+            if (dir.isDirectory()) {
+                String[] files = dir.list();
+                for (int i =0; i < files.length; i++) {
```
Comment (lieut-data) [inline android/app/src/main/java/com/mattermost/share/RealPathUtil.java]: nit: space after `=`?

File: android/app/src/main/java/com/mattermost/share/RealPathUtil.java [hunk 4]
```diff
@@ -172,4 +176,22 @@ public static String getMimeType(String filePath) {
...
+                    String file = files[i];
+                    if (file.startsWith("mmShare") || file.startsWith("tmp")) {
+                        File f = new File(dir, files[i]);
+                        f.delete();
```
Comment (lieut-data) [inline android/app/src/main/java/com/mattermost/share/RealPathUtil.java]: Worth recursing and just trying a `delete()` if `!isDirectory()` after the check on line 183?

File: android/app/src/main/java/com/mattermost/share/ShareModule.java (hunk 2 above)
Comment (enahum) [reply android/app/src/main/java/com/mattermost/share/ShareModule.java]: Temp folder here is required cause by the time this is called we no longer have the context of the activity thus we cannot get the cache folder

File: android/app/src/main/java/com/mattermost/share/ShareModule.java (hunk 1 above)
Comment (enahum) [reply android/app/src/main/java/com/mattermost/share/ShareModule.java]: Will look at making this a Path

File: android/app/src/main/java/com/mattermost/share/RealPathUtil.java (hunk 4 above)
Comment (enahum) [reply android/app/src/main/java/com/mattermost/share/RealPathUtil.java]: I don’t get what you mean here

File: android/app/src/main/java/com/mattermost/share/ShareModule.java (hunk 2 above)
Comment (lieut-data) [reply android/app/src/main/java/com/mattermost/share/ShareModule.java]: In the back of my mind I was thinking: can we dedicate this temp folder exclusively and just recursively delete the entire thing vs. picking out only select files for deletion?

File: android/app/src/main/java/com/mattermost/share/RealPathUtil.java (hunk 4 above)
Comment (lieut-data) [reply android/app/src/main/java/com/mattermost/share/RealPathUtil.java]: May not matter for the use case, but I was basically proposing a recursive deletion strategy for this folder vs. just deleting files at the root

**Comment by enahum** [comment]
@lieut-data changes made

**Comment by lieut-data** [comment]
I like it! Thanks :)
